### ISSUE TITLE
Check contents of manuscript_00099/manuscript_00032

### ISSUE THREAD

**Issue by ajrhitchman** [bodleian/south-asian-mss#7]
We have two catalogue records for MS. Ind. Inst. Sansk. 146(R) - [manuscript_00099](https://south-asian.bodleian.ox.ac.uk/catalog/manuscript_00099) [file on git] (https://github.com/bodleian/south-asian-mss/blob/master/collections/MS-Ind-Inst/ms-ind-inst-sansk-147-r-bhagavatapurana.xml) and [manuscript_00032](https://south-asian.bodleian.ox.ac.uk/catalog/manuscript_00032) [file on git] (https://github.com/bodleian/south-asian-mss/blob/master/collections/MS-Ind-Inst/ms-ind-inst-sansk-146-r-vayupurana.xml). Can you investigate and see which one is correct?

I think manuscript_00099 should be MS. Ind. Inst. Sansk. 147(R), judging by the file names.

**Comment by barb0r** [comment]
Done, it was as you've expected!
